dvc pull 'parts/be-brave-intro.mp4'
dvc pull 'parts/eight techniques.mkv'
dvc pull 'parts/not your cup of tea for perfectionist.mkv'
dvc pull 'parts/not an art result of engineering and techniques.mkv'
dvc pull 'parts/people may redicule you.mkv'
dvc pull 'parts/reading scripts generated from ChatGPT.mkv'
dvc pull 'parts/essential to maintatin resilient mindset.mkv'
dvc pull 'parts/stay confident.mkv'
dvc pull 'parts/act as a proxie just like movie her.mkv'
dvc pull 'parts/eight techniques.mkv'
dvc pull 'parts/intro generated all by ai.mkv'
