dvc add 'video generated from my photo.mkv'
dvc add 'how long it takes to be open to public.mkv'
dvc add 'Video synthetic generation.mkv'
dvc add 'Can you make a living out of creating a YouTube video.mkv'
dvc add 'ask bard How much 2-5 minutes high quality youtube video cost.mkv'
dvc add 'How much YouTube pay for 1,000 views.mkv'
dvc add 'plug into spreadsheet and calculate going from 5K to 100 dollar.mkv'
dvc add 'How long does it take for a youtube video to get views.mkv'
dvc add 'not your cup of tea for perfectionist.mkv'
dvc add 'not an art result of engineering and techniques.mkv'
dvc add 'people may redicule you.mkv'
dvc add 'reading scripts generated from ChatGPT.mkv'
dvc add 'essential to maintatin resilient mindset.mkv'
dvc add 'stay confident.mkv'
dvc add 'act as a proxie just like movie her.mkv'
dvc add 'eight techniques.mkv'
dvc add 'show the tricks in the next 5 to 10 videos.mkv'
dvc add 'Five minutes youtube video in one hour.mkv'
dvc add 'neural networks are stateless.mkv'
dvc add 'context size of chatgpt.mkv'
dvc add 'context is important for llm.mkv'
dvc add 'training or fine tuning llm is very costly.mkv'
dvc add 'zero shot leanring and translation.mkv'
dvc add 'Context size of Large Langauge Models.mkv'
dvc add 'correct english with ChatGPT.mkv'
dvc add 'how long for gpt4 video correction.mkv'
dvc add 'avatar generation.mkv'
dvc add 'synthesia introduction.mkv'
dvc add 'intro to intro video.mkv'
dvc add 'intro generated all by ai.mkv'
dvc add 'synthesia crunchbase.mkv'
dvc add 'synthesia avators are not good enough.mkv'
dvc add 'be-brave-intro.mkv'
dvc push 'video generated from my photo.mkv'
dvc push 'how long it takes to be open to public.mkv'
dvc push 'Video synthetic generation.mkv'
dvc push 'Can you make a living out of creating a YouTube video.mkv'
dvc push 'ask bard How much 2-5 minutes high quality youtube video cost.mkv'
dvc push 'How much YouTube pay for 1,000 views.mkv'
dvc push 'plug into spreadsheet and calculate going from 5K to 100 dollar.mkv'
dvc push 'How long does it take for a youtube video to get views.mkv'
dvc push 'not your cup of tea for perfectionist.mkv'
dvc push 'not an art result of engineering and techniques.mkv'
dvc push 'people may redicule you.mkv'
dvc push 'reading scripts generated from ChatGPT.mkv'
dvc push 'essential to maintatin resilient mindset.mkv'
dvc push 'stay confident.mkv'
dvc push 'act as a proxie just like movie her.mkv'
dvc push 'eight techniques.mkv'
dvc push 'show the tricks in the next 5 to 10 videos.mkv'
dvc push 'Five minutes youtube video in one hour.mkv'
dvc push 'neural networks are stateless.mkv'
dvc push 'context size of chatgpt.mkv'
dvc push 'context is important for llm.mkv'
dvc push 'training or fine tuning llm is very costly.mkv'
dvc push 'zero shot leanring and translation.mkv'
dvc push 'Context size of Large Langauge Models.mkv'
dvc push 'correct english with ChatGPT.mkv'
dvc push 'how long for gpt4 video correction.mkv'
dvc push 'avatar generation.mkv'
dvc push 'synthesia introduction.mkv'
dvc push 'intro to intro video.mkv'
dvc push 'intro generated all by ai.mkv'
dvc push 'synthesia crunchbase.mkv'
dvc push 'synthesia avators are not good enough.mkv'
dvc push 'be-brave-intro.mkv'
