dvc add 'keep transcribed my audio.mkv'
dvc add 'receive feedback on ideas.mkv'
dvc add 'develop mobiel app using gpt4.mkv'
dvc add 'showing google keep.mkv'
dvc add 'how refine Keep entry.mkv'
dvc add 'medical test that can be done at home.mkv'
dvc add 'mental health tests.mkv'
dvc add 'bing mental tests.mkv'
dvc add 'smart watches detection.mkv'
dvc add 'medical root of insomnia.mkv'
dvc add 'saliva or blood test detect insomnia.mkv'
dvc add 'sleep disorder may be genetic.mkv'
dvc add 'trigger a genetic test.mkv'
dvc add 'extend idea on day to day activities.mkv'
dvc push 'keep transcribed my audio.mkv'
dvc push 'receive feedback on ideas.mkv'
dvc push 'develop mobiel app using gpt4.mkv'
dvc push 'showing google keep.mkv'
dvc push 'how refine Keep entry.mkv'
dvc push 'medical test that can be done at home.mkv'
dvc push 'mental health tests.mkv'
dvc push 'bing mental tests.mkv'
dvc push 'smart watches detection.mkv'
dvc push 'medical root of insomnia.mkv'
dvc push 'saliva or blood test detect insomnia.mkv'
dvc push 'sleep disorder may be genetic.mkv'
dvc push 'trigger a genetic test.mkv'
dvc push 'extend idea on day to day activities.mkv'
