dvc add "Can you make a living out of creating a YouTube video.mkv"
dvc add "ask bard How much 2-5 minutes high quality youtube video cost.mkv"
dvc add "How much YouTube pay for 1,000 views.mkv"
dvc add "plug into spreadsheet and calculate going from 5K to 100 dollar.mkv"
dvc add "How long does it take for a youtube video to get views.mkv"
dvc add "show the tricks in the next 5 to 10 videos.mkv"
dvc push "Can you make a living out of creating a YouTube video.mkv.dvc"
dvc push "ask bard How much 2-5 minutes high quality youtube video cost.mkv"
dvc push "How much YouTube pay for 1,000 views.mkv"
dvc push "plug into spreadsheet and calculate going from 5K to 100 dollar.mkv"
dvc push "How long does it take for a youtube video to get views.mkv"
dvc push "show the tricks in the next 5 to 10 videos.mkv"